version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Navya123
      MYSQL_DATABASE: go_notes
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: go_notes_app
    restart: always
    environment:
      DB_USER: root
      DB_PASSWORD: Navya123
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: go_notes
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: go run main.go

volumes:
  db_data:

